name: dummy_api_client
description: Client, parser and models for Dummy API.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http_api_client:
    path: ../http_api_client
  result_type:
    path: ../result_type     
